#!/usr/bin/env python3
"""Generate plugins/flightdeck from the two component plugins.

The bundle is a real plugin directory, not a pointer: ${CLAUDE_PLUGIN_ROOT}
resolves to the installed plugin's own directory, so a bundle whose hooks
referenced files outside itself would break the moment it was installed from a
marketplace.

That means the bundle's contents are COPIES, which is exactly the kind of
duplication that drifts. So it is generated, never hand-edited, and
`--check` fails CI when it is stale — the same contract as any other generated
artifact.

    python3 tools/build_bundle.py            # regenerate
    python3 tools/build_bundle.py --check    # verify freshness, exit 1 if stale
"""
from __future__ import annotations

import filecmp
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMPONENTS = ("ctxmon", "ipc")
BUNDLE = ROOT / "plugins" / "flightdeck"

BANNER = "GENERATED by tools/build_bundle.py - do not edit; edit the component plugin"


def _component_files(name: str) -> list[Path]:
    src = ROOT / "plugins" / name
    out = []
    for p in sorted(src.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(src)
        # The component's own manifest and hook config are merged, not copied,
        # and tests stay with their component.
        if rel.parts[0] in (".claude-plugin", "hooks", "tests"):
            continue
        # Build artefacts are not source. Shipping a stale .pyc inside a plugin
        # would be served to users as if it were code.
        if "__pycache__" in rel.parts or p.suffix in (".pyc", ".pyo"):
            continue
        out.append(p)
    return out


def _merged_hooks() -> dict:
    """Concatenate both components' hook arrays per event.

    Order matters for Stop: ctxmon's records the idle transition in
    milliseconds, while IPC's holds a long-poll rally window of up to 55
    seconds. ctxmon must come first or the phase timestamp other sessions read
    would be up to a minute late.
    """
    merged: dict[str, list] = {}
    for name in COMPONENTS:
        cfg = json.loads((ROOT / "plugins" / name / "hooks" / "hooks.json")
                         .read_text(encoding="utf-8"))
        for event, entries in cfg.get("hooks", {}).items():
            for entry in entries:
                for h in entry.get("hooks", []):
                    h["command"] = h["command"].replace(
                        "/bin/ctxmon", "/bin/ctxmon").replace("/bin/ipc", "/bin/ipc")
                merged.setdefault(event, []).append(entry)
    # No extra top-level keys. A `_comment` banner here was the difference
    # between "Installed" and "the plugin couldn't be loaded": the hook config
    # is schema-validated and an unexpected sibling of `hooks` fails it. The
    # generated-file warning lives in GENERATED.md instead.
    return {"hooks": merged}


def _manifest() -> dict:
    return {
        "name": "flightdeck",
        "description": (
            "Context and quota telemetry plus a cross-session message channel. "
            "Equivalent to installing ctxmon and ipc separately."),
        "version": "0.1.2",
        "author": {"name": "Ultimatrixman",
                   "url": "https://github.com/Ultimatrixman"},
        "homepage": "https://github.com/Ultimatrixman/claude-flightdeck",
        "repository": "https://github.com/Ultimatrixman/claude-flightdeck",
        "license": "MIT",
        "keywords": ["context", "quota", "ipc", "multi-session", "claude-code"],
        # `commands` and `hooks` are deliberately absent. Both live at their
        # auto-discovered default locations (commands/ and hooks/hooks.json),
        # so declaring them adds a second place to keep in sync and nothing
        # else. The official plugins ship no such fields either.
    }


def build(target: Path) -> None:
    if target.exists():
        shutil.rmtree(target)
    (target / ".claude-plugin").mkdir(parents=True)
    (target / "hooks").mkdir(parents=True)
    for name in COMPONENTS:
        src = ROOT / "plugins" / name
        for p in _component_files(name):
            rel = p.relative_to(src)
            dst = target / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, dst)
    _write(target / ".claude-plugin" / "plugin.json",
           json.dumps(_manifest(), indent=2) + "\n")
    _write(target / "hooks" / "hooks.json",
           json.dumps(_merged_hooks(), indent=2) + "\n")
    _write(target / "GENERATED.md",
           f"# {BANNER}\n\nRun `python3 tools/build_bundle.py` after changing "
           f"either component.\n")


def _write(path: Path, text: str) -> None:
    """Write with LF endings on every platform.

    `Path.write_text` translates \\n to CRLF on Windows, so a bundle generated
    there never byte-matches the LF-normalised copy in git and `--check`
    reports it stale forever. `newline=` on write_text is 3.10+, and this
    supports 3.9, hence open().
    """
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def _tree(d: Path) -> set[str]:
    return {str(p.relative_to(d)).replace("\\", "/")
            for p in d.rglob("*") if p.is_file()}


def check() -> int:
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        ref = Path(tmp) / "flightdeck"
        build(ref)
        if not BUNDLE.exists():
            print("STALE: plugins/flightdeck does not exist")
            return 1
        a, b = _tree(ref), _tree(BUNDLE)
        if a != b:
            for missing in sorted(a - b):
                print(f"STALE: missing {missing}")
            for extra in sorted(b - a):
                print(f"STALE: unexpected {extra}")
            return 1
        for rel in sorted(a):
            if not filecmp.cmp(ref / rel, BUNDLE / rel, shallow=False):
                print(f"STALE: differs {rel}")
                return 1
    print("bundle is current")
    return 0


if __name__ == "__main__":
    if "--check" in sys.argv:
        raise SystemExit(check())
    build(BUNDLE)
    print(f"generated {BUNDLE.relative_to(ROOT)} "
          f"({len(_tree(BUNDLE))} files) from {', '.join(COMPONENTS)}")
